env: "local"

database:
  host: "localhost"
  post: 5432
  user: "your_user"
  password: "your_password"
  dbname: "your_db_name"
  sslmode: "disable"

http_server:
  address: "host:port"
  timeout: 4s
  idle_timeout: 60s

kafka:
  brokers: ["localhost:9092"]
  topic: "orders"
  group_id: "order-service"
  auto_offset_reset: "earliest"
  max_attempts: 3
  batch_size: 1
  workers: 1