env: "local"

database:
  host: "localhost"
  post: 5432
  user: "postgres"
  password: "3356"
  dbname: "l0"
  sslmode: "disable"

http_server:
  address: "localhost:8064"
  timeout: 4s
  idle_timeout: 60s

kafka:
  brokers: ["localhost:9092"]
  topic: "orders"
  group_id: "order-service"
  auto_offset_reset: "earliest"
  max_attempts: 3
  batch_size: 1
  workers: 1